apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-
namespace: development

resources:
  - ../../base

patches:
  - path: patch.yaml

secretGenerator:
  - name: tls-cert
    files:
      - tls/
    behavior: replace
  - name: docker-registry
    files:
      - docker/config.json
    type: kubernetes.io/dockerconfigjson
    behavior: replace

configMapGenerator:
  - name: app-config
    files:
      - config/
    behavior: replace